# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/main.go"
  bin = "tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "env", "yaml"]
  exclude_dir = ["tmp", "assets", "vendor", "bin", "build", "deploy"]
  include_dir = []
  exclude_regex = ["_test.go"]
  exclude_file = []
  exclude_unchanged = true
  log = "air.log"
  args_bin = []
  stop_on_error = true
  send_interrupt = false
  delay = 1000
  kill_delay = 500

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true